### ISSUE TITLE
Getting CA.ipynb working

### ISSUE THREAD

**Issue by brysgo** [sol0invictus/Blog_stuff#1]
Hey @sol0invictus - thanks for your help, I've tried cranking up the epochs and saving/reloading the weights, but nothing is working for me. Here is a link to the one I am running:

https://colab.research.google.com/drive/1SGixt0tWOIFJ3s_XwhqkWLqpDCL2h_7X?usp=sharing

**Comment by sol0invictus** [comment]
I can verify that you are indeed right and you end up getting colorful results. Collab I believe uses TF 2.1 and I have been running TF 2.0 . That is the one difference I can see imediately. Let me dig deeper and get back to you.

**Comment by brysgo** [comment]
Thank you!

**Comment by sol0invictus** [comment]
Found the bug. It is the silliest of things. The model is working fine ( I manually tested on a bunch of different configurations). The issue is with the view_test_error function LOL. All you have to do is the remove the np.argmax(). I will update the code with the fix in the evening.

**Comment by brysgo** [comment]
Thank you!

**Comment by brysgo** [comment]
🤦 that was my bad, when I ran it there was a deprecation error, so I added the code they suggested

**Comment by brysgo** [comment]
It works for me now by the way.
